"""Clone and configure the official Marie Next.js frontend for local backend testing.

Upstream source (same app as https://theworldavatar.io/demos/marie/):
  https://github.com/cambridge-cares/TheWorldAvatar/tree/main/QuestionAnswering/QA_ICL/frontend/next_app_marie

Run from repo root:
  python -m demos.setup_marie_frontend
  python -m demos.setup_marie_frontend --install   # also npm install
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
VENDOR = REPO / "vendor"
SPARSE_ROOT = VENDOR / "TheWorldAvatar"
FRONTEND_REL = Path("QuestionAnswering/QA_ICL/frontend/next_app_marie")
TWA_REPO = "https://github.com/cambridge-cares/TheWorldAvatar.git"
ENV_EXAMPLE = REPO / "configs" / "marie_frontend.env.example"


def frontend_dir() -> Path:
    return SPARSE_ROOT / FRONTEND_REL


def _run(cmd: list[str], *, cwd: Path | None = None) -> None:
    print("+", " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


def clone_sparse(*, force: bool) -> Path:
    dest = frontend_dir()
    if dest.is_dir() and (dest / "package.json").is_file():
        print(f"Frontend already present at {dest}")
        return dest
    if SPARSE_ROOT.exists() and force:
        shutil.rmtree(SPARSE_ROOT)
    VENDOR.mkdir(parents=True, exist_ok=True)
    if not SPARSE_ROOT.exists():
        _run(
            [
                "git",
                "clone",
                "--depth",
                "1",
                "--filter=blob:none",
                "--sparse",
                TWA_REPO,
                str(SPARSE_ROOT),
            ]
        )
        _run(
            ["git", "sparse-checkout", "set", str(FRONTEND_REL.as_posix())],
            cwd=SPARSE_ROOT,
        )
    if not (dest / "package.json").is_file():
        raise RuntimeError(f"Expected package.json under {dest}")
    print(f"Cloned upstream frontend to {dest}")
    return dest


def write_env_local(frontend: Path, *, api_base: str, base_path: str) -> Path:
    env_local = frontend / ".env.local"
    lines = [
        "# Generated by demos.setup_marie_frontend — points at MarieCP Flask API",
        f"NEXT_PUBLIC_BACKEND_ENDPOINT={api_base.rstrip('/')}/",
        f"BASE_PATH={base_path}",
        "",
    ]
    env_local.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {env_local}")
    return env_local


def npm_install(frontend: Path) -> None:
    npm = shutil.which("npm")
    if not npm:
        raise RuntimeError("npm not found — install Node.js 20+ and retry with --install")
    _run([npm, "install"], cwd=frontend)


def main() -> None:
    parser = argparse.ArgumentParser(description="Set up official Marie Next.js frontend")
    parser.add_argument(
        "--install",
        action="store_true",
        help="Run npm install in the cloned frontend",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-clone sparse checkout",
    )
    parser.add_argument(
        "--api-base",
        default=os.environ.get("MARIE_FRONTEND_API_BASE", "http://127.0.0.1:8080/demos/marie/api"),
        help="Flask API base URL (no trailing slash required)",
    )
    parser.add_argument(
        "--base-path",
        default=os.environ.get("MARIE_FRONTEND_BASE_PATH", "/demos/marie"),
        help="Next.js BASE_PATH (production TWA uses /demos/marie)",
    )
    args = parser.parse_args()

    frontend = clone_sparse(force=args.force)
    write_env_local(frontend, api_base=args.api_base, base_path=args.base_path)
    favicon_src = REPO / "demos" / "hub" / "favicon.png"
    if favicon_src.is_file():
        public = frontend / "public"
        public.mkdir(parents=True, exist_ok=True)
        shutil.copy2(favicon_src, public / "favicon.ico")
        print(f"Installed TWA favicon at {public / 'favicon.ico'}")

    if args.install:
        npm_install(frontend)

    rel = frontend.relative_to(REPO)
    print()
    print("Official Marie frontend is ready for compatibility testing.")
    print()
    print("Recommended: run Node/npm in WSL/Linux (upstream targets Linux, Node 20+).")
    print("Do not install Node on Windows for this — use WSL instead.")
    print()
    print("WSL — one command (API + Next dev):")
    print("  wsl bash demos/run_marie_compat_wsl.sh setup")
    print("  wsl bash demos/run_marie_compat_wsl.sh")
    print()
    print("WSL — two terminals:")
    print("  wsl bash demos/run_marie_compat_wsl.sh api")
    print("  wsl bash demos/run_marie_compat_wsl.sh frontend")
    print()
    print(f"Frontend path (WSL): /mnt/c/Users/.../MarieCP/{rel.as_posix()}")
    print("Open: http://127.0.0.1:3000/demos/marie/")
    print("Verify API: python -m demos.verify_marie_frontend_compat")
    print()
    print(f"Upstream: {TWA_REPO} (path {FRONTEND_REL.as_posix()})")


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        sys.exit(exc.returncode)
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
